const chemicalData = [
    {
      id: 1,
      name: "Ammonium Persulfate",
      vendor: "LG Chem",
      density: 3525.92,
      viscosity: 60.63,
      packaging: "Bag",
      packSize: 100,
      unit: "kg",
      quantity: 6495.18,
    },
    {
      id: 2,
      name: "Caustic Potash",
      vendor: "Formosa",
      density: 3172.15,
      viscosity: 48.22,
      packaging: "Bag",
      packSize: 100,
      unit: "kg",
      quantity: 8751.9,
    },
    {
      id: 3,
      name: "Dimethyl-aminopropylamine",
      vendor: "LG Chem",
      density: 835.37,
      viscosity: 12.62,
      packaging: "Barrel",
      packSize: 75,
      unit: "L",
      quantity: 5964.61,
    },
    {
      id: 4,
      name: "Mono Ammonium Phosphate",
      vendor: "Sinopec",
      density: 1597.65,
      viscosity: 76.51,
      packaging: "Bag",
      packSize: 105,
      unit: "kg",
      quantity: 8183.73,
    },
    {
      id: 5,
      name: "Ferric Nitrate",
      vendor: "DowDuPont",
      density: 364.04,
      viscosity: 14.9,
      packaging: "Bag",
      packSize: 105,
      unit: "kg",
      quantity: 4154.33,
    },
    {
      id: 6,
      name: "n-Pentane",
      vendor: "Sinopec",
      density: 4535.26,
      viscosity: 66.76,
      packaging: "N/A",
      packSize: "N/A",
      unit: "t",
      quantity: 6272.34,
    },
    {
      id: 7,
      name: "Glycol Ether PM",
      vendor: "LG Chem",
      density: 6495.18,
      viscosity: 72.12,
      packaging: "Bag",
      packSize: 250,
      unit: "kg",
      quantity: 8749.54,
    },
    {
      id: 8,
      name: "Sodium Hypochlorite",
      vendor: "BASF",
      density: 1190.0,
      viscosity: 1.5,
      packaging: "Drum",
      packSize: 200,
      unit: "L",
      quantity: 7500.0,
    },
    {
      id: 9,
      name: "Hydrochloric Acid",
      vendor: "Solvay",
      density: 1180.0,
      viscosity: 1.0,
      packaging: "Drum",
      packSize: 250,
      unit: "L",
      quantity: 6000.0,
    },
    {
      id: 10,
      name: "Sodium Hydroxide",
      vendor: "Dow Chemical",
      density: 2130.0,
      viscosity: 1.5,
      packaging: "Bag",
      packSize: 50,
      unit: "kg",
      quantity: 10000.0,
    },
    {
      id: 11,
      name: "Sulfuric Acid",
      vendor: "BASF",
      density: 1840.0,
      viscosity: 1.5,
      packaging: "Drum",
      packSize: 300,
      unit: "L",
      quantity: 8000.0,
    },
    {
      id: 12,
      name: "Nitric Acid",
      vendor: "Solvay",
      density: 1513.0,
      viscosity: 1.0,
      packaging: "Drum",
      packSize: 200,
      unit: "L",
      quantity: 5000.0,
    },
    {
      id: 13,
      name: "Phosphoric Acid",
      vendor: "Dow Chemical",
      density: 1685.0,
      viscosity: 1.5,
      packaging: "Drum",
      packSize: 250,
      unit: "L",
      quantity: 7000.0,
    },
    {
      id: 14,
      name: "Acetic Acid",
      vendor: "BASF",
      density: 1049.0,
      viscosity: 1.0,
      packaging: "Drum",
      packSize: 200,
      unit: "L",
      quantity: 6000.0,
    },
    {
      id: 15,
      name: "Sodium Carbonate",
      vendor: "Solvay",
      density: 2500.0,
      viscosity: 1.5,
      packaging: "Bag",
      packSize: 50,
      unit: "kg",
      quantity: 12000.0,
    },
  ];
  